# 06_Unsupervised_Model_Development_LDA

In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
import matplotlib.pyplot as plt
from sklearn.decomposition import TruncatedSVD
from sklearn.decomposition import LatentDirichletAllocation
import polars as pl
import joblib
from gensim.corpora import Dictionary
import duckdb

In [4]:
# Load the parquet file
INPUT_PATH = '../data/processed/clustered_narratives.parquet'
df_narratives = pd.read_parquet(
    INPUT_PATH,
    columns=[
        'Complaint ID',
        'processed_narrative'
    ]
)

In [5]:
df_narratives.head()

   Complaint ID                                processed_narrative
0       3442136  claimed delivered package address never receiv...
1       3601853  got brink money pre paid card mail assuming un...
2       3300820  called creditor nelson cruz associate claimed ...
3       3739698  around opened credit card account online capit...
4       3285243  equifax sent credit card suggestion help impro...

In [6]:
print(len(df_narratives))

398004

## Train/Transform Vectorizer and LDA on 50k Sample

In [25]:
# # Company stopwords
# company_stopwords = { 'goldman', 'sachs', 'one', 'chase', 'well', 'fargo', 'capital', 'america', 'citibank', 'citi', 'jpmorgan', 'navy', 'federal', 'union'}

In [26]:
# # Train Count Vectorizer on 50k sample to save memory
# df_lda_sample = df_narratives.sample(
#     n=50_000,
#     random_state=42
# )
#
# count_vectorizer = CountVectorizer(
#     min_df=20,
#     max_df=0.90,
#     max_features=10_000,
#     # stop_words=list(company_stopwords)
# )
#
# X_count = count_vectorizer.fit_transform(
#     df_lda_sample['processed_narrative']
# )
#
# print(X_count.shape)

(50000, 6299)

In [7]:
# If re-running notebook, load the trained Vectorizer
count_vectorizer = joblib.load('count_vectorizer.pkl')

In [8]:
# Transform without re-training the Vectorizer
df_lda_sample = df_narratives.sample(
    n=50_000,
    random_state=42
)

X_count = count_vectorizer.transform(
    df_lda_sample['processed_narrative']
)

print(X_count.shape)

(50000, 6299)

In [10]:
# # Train LDA on sample
# # n_components = 20 was identified by the grid search later in the notebook.
# lda = LatentDirichletAllocation(
#     n_components=20,
#     learning_method='online',
#     random_state=42,
#     n_jobs=-1,
#     batch_size=2048
# )
#
# lda.fit(X_count)

In [11]:
# If re-running notebook, load the trained LDA model
lda = joblib.load('lda_model.pkl')

## Examine Topic Terms

In [12]:
# Print top terms in the LDA topics
feature_names = np.array(count_vectorizer.get_feature_names_out())

for topic_idx, topic in enumerate(lda.components_):
    top_indices = topic.argsort()[::-1][:15]
    top_terms = feature_names[top_indices]

    print(f'\nTopic {topic_idx}')
    print(', '.join(top_terms))

Topic 0
financial, issue, complaint, account, request, despite, matter, regarding, customer, resolution, action, provide, without, service, concern

Topic 1
payment, late, account, due, pay, fee, paid, made, balance, month, statement, amount, credit, time, bill

Topic 2
told, said, call, back, get, would, called, time, account, money, could, phone, asked, day, number

Topic 3
mortgage, loan, property, escrow, tax, servicing, foreclosure, servicer, shellpoint, borrower, document, notice, court, request, payment

Topic 4
account, bank, closed, checking, transfer, fund, would, citibank, saving, day, told, close, money, access, received

Topic 5
charge, card, letter, received, credit, sent, fraud, discover, fraudulent, called, email, made, number, call, statement

Topic 6
credit, card, account, limit, score, report, closed, synchrony, bank, balance, year, never, application, reason, apple

Topic 7
reporting, credit, information, account, report, consumer, debt, act, agency, inaccurate, reported, fair, collection, dispute, bureau

Topic 8
card, one, credit, capital, would, service, use, customer, purchase, told, called, new, could, time, used

Topic 9
account, one, capital, number, name, address, identity, information, fraud, security, opened, card, theft, report, credit

Topic 10
refund, dispute, citi, merchant, item, received, credit, purchase, order, company, never, card, paypal, charge, back

Topic 11
chase, money, bank, account, claim, fraud, transaction, atm, card, back, police, debit, cash, report, stolen

Topic 12
transaction, dispute, claim, unauthorized, merchant, bank, charge, investigation, chime, evidence, documentation, denied, provided, fraud, year

Topic 13
mortgage, loan, home, would, company, insurance, year, time, document, month, told, sent, payment, received, pay

Topic 14
well, fargo, interest, balance, rate, charge, month, purchase, statement, amount, promotional, charged, would, transfer, card

Topic 15
american, express, bonus, offer, usaa, amex, point, reward, account, term, day, promotion, would, received, receive

Topic 16
ticket, car, flight, rental, vehicle, airline, travel, trip, refund, repair, reservation, charge, usd, key, paid

Topic 17
consumer, law, act, federal, right, credit, security, state, violation, bank, action, agreement, practice, contract, notice

Topic 18
fee, account, overdraft, charged, charge, transaction, bank, balance, navy, federal, fund, union, negative, credit, deposit

Topic 19
check, bank, fund, account, america, deposit, branch, day, deposited, money, hold, would, told, business, received

In [13]:
# Add dominant topic to the sample dataframe.
# Add topic_probability which ONLY contains the probability of the dominant topic
topic_probs = lda.transform(X_count)

df_lda_sample['dominant_topic'] = topic_probs.argmax(axis=1)
df_lda_sample['topic_probability'] = topic_probs.max(axis=1)

df_lda_sample['dominant_topic'].value_counts().sort_index()

dominant_topic
0     2486
1     3994
2     9063
3      747
4     4502
5     2289
6     2310
7     1350
8     1992
9     2388
10    2406
11    2889
12    2417
13    2474
14    1111
15    1510
16      78
17     819
18    1799
19    3376
Name: count, dtype: int64

In [14]:
df_lda_sample.head()

,Complaint ID,processed_narrative,dominant_topic,topic_probability
102450,7148773,complain open bank texas day ago received regu...,9,0.300276
78236,5432970,well fargo credit card file police report repo...,11,0.495463
384187,3850335,unresolved issue citibank lasted two month sti...,4,0.435029
272901,12076787,checked account today noticed encoding error c...,19,0.418023
382568,7974309,account saving checking account closed know st...,4,0.601591

## Inspect Sample Narratives

In [15]:
# Load in cleaned narratives for the Complaint ID's in the LDA 50k sample
sample_ids = df_lda_sample['Complaint ID'].to_list()

df_readable = (
    pl.scan_parquet(INPUT_PATH)
    .filter(pl.col('Complaint ID').is_in(sample_ids))
    .select([
        'Complaint ID',
        'cleaned_consumer_narrative'
    ])
    .collect()
    .to_pandas()
)

df_lda_sample = df_lda_sample.merge(
    df_readable,
    on='Complaint ID',
    how='left'
)

In [16]:
print(df_lda_sample.columns.tolist())

['Complaint ID', 'processed_narrative', 'dominant_topic', 'topic_probability', 'cleaned_consumer_narrative']

In [17]:
# Print and inspect example narratives in each topic
for topic in sorted(df_lda_sample['dominant_topic'].unique()):
    print(f'\n===== Topic {topic} =====')

    samples = (
        df_lda_sample[df_lda_sample['dominant_topic'] == topic]
        .sample(n=3, random_state=42)
    )

    for text in samples['cleaned_consumer_narrative']:
        print('\n', text[:500])

===== Topic 0 =====

 In early REDACTED / REDACTED /year>, American Express suddenly closed all of my personal and business credit cards, as well as my charge cards, after I was told that my financial review had not been approved. I had been an American Express customer in good standing for several years, with no missed or late payments, and I always paid my balances in full or on time. During the financial review, I was asked to provide documents verifying my income and financial capability. I submitted all requeste

 On REDACTED / REDACTED /year> my Bank of America account was suddenly blocked without any prior warning or notification.What happened before the account closure : Shortly before the account was blocked, I received a REDACTED transfer for {$660.00} from a friend named REDACTED REDACTED . This money was payment for a personal debt he owed me - a legitimate transaction between friends.The only other unusual activity on my account was that I had been using it in two locations outside the United Stat

 On REDACTED I visited the Wells Fargo branch in REDACTED REDACTED REDACTED to request notary service only. I waited calmly and was assisted by a banker ( REDACTED ) who initially stated she could help me. While walking to the desk, the banker asked about an item in my hand. I informed her it was a recorder and stated it was not turned on. After sitting down, she briefly looked at my documents and asked whether they had anything to do with Wells Fargo. I stated they did not and offered for her to

===== Topic 1 =====

 On REDACTED_DATE my Kohls charge card was due. Previously around the REDACTED of that month I had set up Autopay and it did not go through for whatever reason. I noticed on REDACTED_DATE and paid the {$27.00}. On REDACTED_DATE , when trying to make REDACTED_DATE payment I noticed there was a {$56.00} minimum payment due to late fee. I called Kohls and talked to 2 representatives, and all told me they waived the late fee since I rarely miss a payment and am a preferred customer, however I would s

 Citi has closed my double cash card account in retaliation for me withdrawing my deposits and closing my checking and savings accounts. They have closed my account without notifying me and without just cause. They have revoked my access to make payments online, and refuse to send me statements. When I call the number on the back of the card to make my payments, their automated system malfunctions and does not allow me to make my payments. Since I am not receiving my statements, can not pay onlin

 I had 3 credit cards with Chase Card Services for several years. On one occasion it happened with 1 credit card that my payment got rejected by my bank where I had the checking account because of insufficient funds. Chase than made it impossible for me tomake payments on this one card in the future online. ( although I had paid off all the other credit cards and the balance there is REDACTED now. ) I contacted Chase several times online but they never answered. They charged me late fees and inte

===== Topic 2 =====

 In REDACTED my citi bank debit card was locked due to suspicion of fraud because i was spending more than normal when I attempted to call citi bank and unlock my card they would not do so saying i had to go to a branch and provide documents to prove my identity I obliged and went to the branch with my ID and birth certificate and also my medical card the branch told me to allow 24 hours and my card would b unlocked ... that never happened i called back to b told my account is being closed and an

 On REDACTED_DATE the Florida REDACTED issued me my backpay of {$3500.00} and it went to direct deposit to my PayPal account which they use REDACTED REDACTED at superstore you account and I have no problems ever getting direct deposit with them The account number and the routing number is correct everything is correct its just the money is not even showing up at all apparently to PayPal and they are not doing anything about it they said they cant do anything about it my money is just missing and

 I go to REDACTED REDACTED and they use Bankmobile as the bank they release your funds to. I have tried several times to open an account with them and they always deny me and refuse to tell me why as required by federal law claiming it is the security department 's problem. Now every time I get my financial aid refund I have to cuss, rant, rave, and threaten a lawsuit and you all to get my money released and my profile found which after 5 minutes of hanging up from being constantly routed to an a

===== Topic 3 =====

 We had a 15 year commercial loan on our real estate office. We sold the building after 6 years and paid off the balance of the mortgage. We were charged {$25000.00} pre-payment penalty on the balance of {$210000.00}. The original loan was for {$300000.00}. The note on the mortgage that was signed was very ambiguous and we never expected this huge prepayment penalty. We have been customers of this bank for over 45 years, and had all of our accounts with them. We were referred to you by REDACTED R

 REDACTED REDACTED REDACTED the closing attorney has requested payoff statement for the closing on REDACTED_DATE on REDACTED REDACTED , REDACTED and REDACTED_DATE , we were on the phone a REDACTED way call on REDACTED_DATE for over an hour with m & t bank and them promising to provide payoff statement by Monday REDACTED and failed to do so. Also just to mention the loan is in my maiden name REDACTED REDACTED .

 Name of the loan servicer : Mr Cooper According to Mr Cooper, all calls are recorded. No transcripts have been provided. REDACTED_DATE Receive Loan Modification Acceptance documents REDACTED_DATE contact Mr Cooper to discuss and ask questions REDACTED_DATE Signed acceptance of loan modification REDACTED_DATE returned the signed Loan Modification Acceptance documents REDACTED_DATE New modified payment is available on Online account for payment REDACTED_DATE Online Mr Cooper Account reflects no ch

===== Topic 4 =====

 I closed my account 2+ months ago. However I am now still receiving paper statements in the mail for this closed account, as if it never was closed. I can not log in to my online account to contact BofA, because the account was " closed '' and so it says there's no account to log in to anymore.

 Frost Bank called to confirm if an online account had been opened in my name. I said no and they are to close the account. They suggested I report to FTC.

 On REDACTED / REDACTED /2022 My husband and I received an email from our joint Capital One Bank, indicating that they are immediately closing our checking and savings account due to inconsistant activity, with no other explanations. They sent the email addressing it only to my husband, letting him know that he is allowed to open a new account, but his wife is not. Do you know how that makes me feel? Like I did something wrong? My husband and I have been married for over 30 years and we always ha

===== Topic 5 =====

 My wall mart credit? capitol one card was reported lost/stolen late REDACTED of 2019. On janruary REDACTED two charges were made at store REDACTED tchopotouloosuy wallmart one for REDACTED and the other for REDACTED the posted on janruary REDACTED .and are associated with a card ending in REDACTED , However after there investigation i recieved a letter six weeks later claiming recieved some sort of benefit from the loss of this card and its costs. This is not true. and i would like them to place

 I have notice discover was reporting an fraudulent account in 2017 so while REDACTED i been working on removal. discover removed account then all of a sudden they keep changing account number i contact REDACTED they stated the open dates all was the same but close dated was different i have paperwork from discover stating removal and accounts all of them was fraudulent

 REDACTED flagged my REDACTED received payment as fraud and it wasnt fraud and after verifiying with the third party who sent it and provided proof Truist still not willing to fix their mess up

===== Topic 6 =====

 Citibank arbitrarily lowered my credit limit from {$2500.00} to {$880.00} for no good reason. I have been a customer of Citibank credit since REDACTED / REDACTED /2023. I have paid my bills on time every month. Yet, in under a year of being a customer of the bank, they took away most of the very reason I'm with them : my credit. Furthermore, I have paid my credit card bills on time, every month, with all other bank credit cards outside Citibank. There is no good justification for the reduction o

 I obtained this credit card to be able to finance a piece of furniture. I since have paid off my debt with them and was considering whether or not I should keep the account open. While I thought about my decision I reached out to the company asking how I would go about closing my account if i decided to do so. I did not at any moment ask them to close my account nor consent or sign anything agreeing for it to be closed. In the following days I got notifications from them saying that my account w

 Amazon offered {$60.00} credit if applied for credit JPMC Chase REDACTED_DATE applied for credit no instant approval Need street address Emailed copy of Texas drivers license REDACTED / REDACTED / letter receive REDACTED_DATE could not read drivers license REDACTED_DATE Went in to bank branch and they faxed copy of drivers license confirmed they received the copy REDACTED_DATE received letter to contact them with phone number It looks like a delay tactic. If they give me the {$60.00} they can ke

===== Topic 7 =====

 I have identified late payment entries on my credit report that I believe are incorrect. According to 15 USC 1681e ( b ) and 15 USC 1681i, my credit file must include only data that is accurate, complete, and verifiable. I am formally requesting verification of these entries, and if they can not be substantiated, I ask that they be corrected or deleted.

 I believe the account is invalid. CCB/CHLDPLCE needs to verify under oath that this claim is valid, free from any claims and defenses including but not limited to any breach of agreement, failure of consideration, or material alterations, and that the original lender provided value. Further, the alleged account was transferred in good faith and with the consent of all parties involved. If they are unable to provide under oath the previously listed item then I require the account to be removed fr

 I am submitting this complaint as a follow-up to a prior dispute regarding late payment reporting on my Citi account ending in REDACTED . Citi responded stating that the late payments were reported accurately and provided copies of billing statements. However, their response does not include sufficient documentation to support the accuracy of the reported late payments. While Citi provided statements showing due dates and payment posting dates, they did not provide : Documentation showing when t

===== Topic 8 =====

 Subject : bait-and-switch scheme RE : REDACTED REDACTED REDACTED card REDACTED REDACTED REDACTED REDACTED Transaction Date : REDACTED / REDACTED /2023 Amount Paid : REDACTED Payment Method : Barclay Credit Card I agreed and confirmed that the price for car rental was {$280.00}. ( see attached ) Upon arrival to pick up the car, I was requested to pay an additional {$170.00}. I refused to pay, did not take car delivery, and left the office. REDACTED REDACTED REDACTED REDACTED runs a classic bait-a

 Date of incident REDACTED / REDACTED /2023 Kohl 's recently partnered with Capital One to handle credit card payments for them. Until today I would have had an option to use my Kohl 's card or the Kohl 's VISA card with Capital One when I logged in. Today the only option I had was the Kohl 's VISA card. When I tried to use the Kohls VISA while shopping online, it said I had to connect the card. In order to connect my card I had to enter the account expiration date and security code. I didn't hav

 I was supposed to receive a pre-paid credit/debit card for {$2000.00} for a rebate on the purchase of new appliances through REDACTED REDACTED . My rebate email status told me a card was to be mailed in REDACTED_DATE and received sometime in REDACTED_DATE . REDACTED REDACTED REDACTED , then sent the prepaid card to an address that was not listed on my rebate in any fashion, to a residence that I did not live. In late REDACTED_DATE or early REDACTED_DATE , I called REDACTED REDACTED REDACTED to i

===== Topic 9 =====

 My account was closed with out me being properly notified. I didnt receive a email nor mail that my account was closed. I called capital one to solve the issue. I was told that they couldnt open my account back up. By law protecting the customer using the far reporting credit act I should be properly notified any changes to my account. I should be notified in 21 days.which I was not. I am enrolled into paperless documentation and I dont have emails being sent to my email to any changes to my acc

 My identity was stolen and I have no knowledge of the accounts.

 In REDACTED of 2021. I incurred a problem with CHIME bank. I was asked to upload a copy of social security, a copy of my driver 's license, and a copy showing PROOF of residency. They changed my arm pin number without my consent. They blocked me from getting into my account.. Two days ago I sent several emails telling them to close my account. Every since then, I have been logged out of my other bank account. My accounts and email have been hacked, breached, and compromise. On their website they

===== Topic 10 =====

 this is dated last REDACTED / REDACTED /2020. regarding the credit amount of {$4800.00} plus transaction fee and penalty fee. because they didn't resolved the disputed amount but I sent already and provide all the documents that they request. the reason why I wanted to refund was because I was in a subtle way cheated and deceived with all of my hard earned money. In fact, I have an evidence to prove that they were lying about the price on their website. The price has not been updated up until no

 on REDACTED / REDACTED /19 I opened up REDACTED disputes against REDACTED and REDACTED REDACTED REDACTED from my Chase credit card. Chase has all the dispute information in their file. REDACTED the merchandise was returned because it was defective. I never received a replacement or credit. When I left the defective merchandise I was told someone would contact me which never happened. For REDACTED REDACTED these were not my charges. Chase contacted me about these charges and the agent was incredi

 I was scammed from a merchant for a total of {$9000.00}. Ive contacted Navy Federal multiple times to receive a refund. Ive presented all of the documents that was requested, including an email stating that I will be getting a refund. I never gotten a refund from the merchant nor my banking institution, its a total of three months and I have been fighting and waiting to get this issue resolved and refunded

===== Topic 11 =====

 On the date of REDACTED_DATE I received a fraudulent phone call that was coming directly from the CHASE Bank fraud department. It was a person who claimed to be a worker from CHASE Bank 's fraud department stating that there was an unauthorized wire attempt taking place on my bank account, at the moment I was caught off guard and working so I took the call very serious since CHASE makes phone calls when there is fraudulent activity taking place in my account, however, in my case the person who w

 Me and my granddaughter share an account at Navy Federal, I had to be out on the account because she was a minor at the time and they needed a joint signer so I signed up with her. We have this account opened for quite sometime, then one day I noticed the account was drained and I got a letter from Navy Fed telling me they will start taking money out of my other accounts if this is not paid. I spoke with them and found out an {$8000.00} check was deposited but we did not do this deposit. I dispu

 REDACTED / REDACTED /2020 - I opened Checking and Savings accounts with Citibank. I transferred {$2000.00} to Checking account. REDACTED / REDACTED /2020 - Someone stole letters with a Citibank debit card and a pin code. REDACTED / REDACTED /2020 - Someone used the stolen debit card to make purchases in REDACTED and REDACTED in the amount of {$640.00}. REDACTED / REDACTED /2020 - I checked balance and found unauthorized transactions in my account. I locked the debit card immediately, called to C

===== Topic 12 =====

 Original Issue : My wifes debit card was compromised and they took several dollar amounts out before Capital One 's fraud detection caught it. The original compromise happened on REDACTED / REDACTED /year>,, we immediately filed a dispute, with the fraud case # REDACTED We were given the temporary credit on REDACTED / REDACTED /year>, for {$330.00}. I disputed the charges and they gave me a provisional credit. We were then able to get the issue resolved and the money was returned to our account.

 On REDACTED / REDACTED /year>, I disputed transactions with Chase related to REDACTED REDACTED REDACTED . Chase later confirmed the disputed amounts were refunded and provided two Visa Acquirer Reference Numbers ( ARNs ) for the returned funds : {$1400.00} ARN : REDACTED {$1300.00} ARN : REDACTED Despite this, the merchant ( Hard Rock Bet ) has confirmed they can not locate or credit the funds using these ARNs. Chase has refused to perform a REDACTED transaction trace or merchant research reques

 I've been charged {$460.00} in fraudulent charges on my account and my bank provider has denied to credit for the fraud because I have no evidence supporting my claim. Ive contacted them on multiple occasions to appeal my account and they're not contacting me back for over 72 hours. I can not contact the company who applied charges to my account because they are out of country.

===== Topic 13 =====

 Was told online through myloans that i was on a forbearance until REDACTED_DATE . I did not make a payemnt due to being in forbarence which was told by flagstar I was not in forbarence but online said I was. Stated on myloans " on active forbarence until REDACTED I have been trying to resovle this for a year now and they have me as active foreclosure. They did not tell me that I had a morgage modification in REDACTED or REDACTED_DATE REDACTED so now the loss mitigation team will not work with me

 M & T Bank employee REDACTED REDACTED ID REDACTED on REDACTED_DATE did my verbal eligibility intake over the phone for the Unemployment Forbearance Plan of which she explained to me as I wrote down notes as to how to works. It's a REDACTED month plan that is given in REDACTED month increments and at beginning of last month of each REDACTED month increment, u have to call in for an extension is still needed. First of they only gave me 2 months starting REDACTED_DATE , then I called in request ext

 We received a letter in REDACTED of REDACTED that Fay Servicing was our new servicer for our mortgage which was REDACTED REDACTED REDACTED . We had been with REDACTED REDACTED REDACTED for years and we were pretty close to paying off our mortgage. Once REDACTED took over the mortgage, they started demanding the full amount of more than the loan was ever for. We purchased our home in REDACTED and started payments around REDACTED and had never refinanced our mortgage or anything. The original loan

===== Topic 14 =====


## Get Topic Coherence Score on Current Model

In [35]:
# tokenized_docs = (
#     df_lda_sample['processed_narrative']
#     .str.split()
#     .tolist()
# )
#
# dictionary = Dictionary(tokenized_docs)

In [36]:
# topics = []
#
# for topic in lda.components_:
#
#     top_indices = topic.argsort()[::-1][:15]
#
#     topics.append(
#         [feature_names[i] for i in top_indices]
#     )

In [37]:
# from gensim.models.coherencemodel import CoherenceModel
#
# coherence_model = CoherenceModel(
#     topics=topics,
#     texts=tokenized_docs,
#     dictionary=dictionary,
#     coherence='c_v'
# )
#
# coherence_score = coherence_model.get_coherence()
#
# print(f'Coherence Score: {coherence_score:.4f}')

Coherence Score: 0.4901

## Search for Best Coherence Score

This section searches across different values of `n_topics` using the existing 50k LDA sample, `count_vectorizer`, `X_count`, and `feature_names`.

The search evaluates each model with Gensim's `c_v` coherence score. Higher coherence is better.

In [18]:
# # Helper function to extract top words from each fitted LDA topic
# def get_lda_topics(
#     lda_model,
#     feature_names,
#     n_top_words=15
# ):
#     topics = []
#
#     for topic in lda_model.components_:
#         top_indices = topic.argsort()[::-1][:n_top_words]
#         top_words = [feature_names[i] for i in top_indices]
#         topics.append(top_words)
#
#     return topics

In [19]:
# from gensim.models.coherencemodel import CoherenceModel
#
# # Use the existing LDA sample for coherence scoring
# tokenized_docs = (
#     df_lda_sample['processed_narrative']
#     .fillna('')
#     .str.split()
#     .tolist()
# )
#
# dictionary = Dictionary(tokenized_docs)
#
# lda_coherence_results = []
#
# for n_topics in [5, 10, 15, 20, 25, 30]:
#
#     lda_search = LatentDirichletAllocation(
#         n_components=n_topics,
#         learning_method='online',
#         random_state=42,
#         n_jobs=-1,
#         batch_size=2048
#     )
#
#     lda_search.fit(X_count)
#
#     topics = get_lda_topics(
#         lda_model=lda_search,
#         feature_names=feature_names,
#         n_top_words=15
#     )
#
#     coherence_model = CoherenceModel(
#         topics=topics,
#         texts=tokenized_docs,
#         dictionary=dictionary,
#         coherence='c_v'
#     )
#
#     coherence_score = coherence_model.get_coherence()
#
#     lda_coherence_results.append({
#         'n_topics': n_topics,
#         'coherence_c_v': coherence_score,
#         'perplexity': lda_search.perplexity(X_count)
#     })
#
#     print(
#         f'n_topics={n_topics}, '
#         f'coherence_c_v={coherence_score:.4f}'
#     )
#
# lda_coherence_results_df = pd.DataFrame(lda_coherence_results)
#
# lda_coherence_results_df = lda_coherence_results_df.sort_values(
#     by='coherence_c_v',
#     ascending=False
# )
#
# lda_coherence_results_df

n_topics=5, coherence_c_v=0.4553
n_topics=10, coherence_c_v=0.4818
n_topics=15, coherence_c_v=0.4882
n_topics=20, coherence_c_v=0.4901
n_topics=25, coherence_c_v=0.4795
n_topics=30, coherence_c_v=0.4499

   n_topics  coherence_c_v  perplexity
3        20       0.490149  869.956905
2        15       0.488172  881.202929
1        10       0.481773  904.203078
4        25       0.479543  864.910800
0         5       0.455305  957.083565
5        30       0.449877  867.629379

In [38]:
# # Optional: save the topic coherence search results
# COHERENCE_RESULTS_PATH = '../data/processed/lda_topic_coherence_search.csv'
#
# lda_coherence_results_df.to_csv(
#     COHERENCE_RESULTS_PATH,
#     index=False
# )
#
# print(f'LDA coherence search results saved to: {COHERENCE_RESULTS_PATH}')

## Add Topic Probabilities for the 50k Sample as Features

In [18]:
# Create a dataframe with the probabilities of each topic
topic_features = pd.DataFrame(
    topic_probs,
    columns=[
        f'topic_{i}_prob'
        for i in range(topic_probs.shape[1])
    ]
)

# Horizontal concatenation - brings the topic probability columns into the original sample dataframe
df_lda_sample = pd.concat(
    [df_lda_sample.reset_index(drop=True),
     topic_features.reset_index(drop=True)],
    axis=1
)

df_lda_sample.head()

,Complaint ID,processed_narrative,dominant_topic,topic_probability,cleaned_consumer_narrative,topic_0_prob,topic_1_prob,topic_2_prob,topic_3_prob,topic_4_prob,...,topic_10_prob,topic_11_prob,topic_12_prob,topic_13_prob,topic_14_prob,topic_15_prob,topic_16_prob,topic_17_prob,topic_18_prob,topic_19_prob
0,7148773,complain open bank texas day ago received regu...,9,0.300276,I have a complain open No REDACTED against Ban...,0.043817,0.000485,0.296702,0.000485,0.000485,...,0.000485,0.000485,0.000485,0.152601,0.000485,0.000485,0.000485,0.000485,0.000485,0.000485
1,5432970,well fargo credit card file police report repo...,11,0.495463,Wells Fargo credit card {$3500.00} REDACTED / ...,0.002941,0.002941,0.002941,0.002941,0.002941,...,0.002941,0.495463,0.002941,0.002941,0.260341,0.002941,0.002941,0.002941,0.002941,0.002941
2,3850335,unresolved issue citibank lasted two month sti...,4,0.435029,My unresolved issues with CitiBank have now la...,0.000099,0.000099,0.238830,0.000099,0.435029,...,0.030489,0.000099,0.071104,0.000099,0.000099,0.171067,0.000099,0.000099,0.000099,0.000099
3,12076787,checked account today noticed encoding error c...,19,0.418023,I checked my account today and noticed that th...,0.000446,0.000446,0.166560,0.000446,0.000446,...,0.000446,0.000446,0.151287,0.000446,0.164227,0.000446,0.000446,0.000446,0.044577,0.418023
4,7974309,account saving checking account closed know st...,4,0.601591,My account savings and checking account was cl...,0.003125,0.003125,0.003125,0.003125,0.601591,...,0.003125,0.342159,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125

In [20]:
# Cut down the sample dataframe to only the LDA features,
# e.g., removing narrative columns.
lda_features_sample = df_lda_sample[
    ['Complaint ID', 'dominant_topic']
    + [
        col for col in df_lda_sample.columns
        if col.startswith('topic_')
    ]
].copy()

## Apply LDA to the Remaining Records

In [21]:
# Identify remaining records outside of initial LDA sample
remaining_mask = ~df_narratives['Complaint ID'].isin(
    df_lda_sample['Complaint ID']
)

df_lda_remaining = df_narratives.loc[
    remaining_mask,
    ['Complaint ID', 'processed_narrative']
].copy()

print(f'Remaining records: {len(df_lda_remaining):,}')

Remaining records: 348,004

In [22]:
# Apply LDA to the remaining records without re-training
batch_size = 50_000
feature_batches = []

for start in range(0, len(df_lda_remaining), batch_size):
    end = min(start + batch_size, len(df_lda_remaining))

    print(f'Processing rows {start:,} to {end:,}...')

    batch = df_lda_remaining.iloc[start:end]

    X_batch = count_vectorizer.transform(
        batch['processed_narrative']
    )

    topic_probs = lda.transform(X_batch)

    topic_features = pd.DataFrame(
        topic_probs,
        columns=[
            f'topic_{i}_prob'
            for i in range(topic_probs.shape[1])
        ]
    )

    topic_features['Complaint ID'] = batch['Complaint ID'].values
    topic_features['dominant_topic'] = topic_probs.argmax(axis=1)

    feature_batches.append(topic_features)

Processing rows 0 to 50,000...
Processing rows 50,000 to 100,000...
Processing rows 100,000 to 150,000...
Processing rows 150,000 to 200,000...
Processing rows 200,000 to 250,000...
Processing rows 250,000 to 300,000...
Processing rows 300,000 to 348,004...

In [42]:
# # Write fitted Count Vectorizer and LDA to file
# joblib.dump(
#     count_vectorizer,
#     'count_vectorizer.pkl'
# )
#
# joblib.dump(
#     lda,
#     'lda_model.pkl'
# )

['lda_model.pkl']

## Combine the Sample Dataframe with the Remaining Dataframe

In [23]:
# Stack the dataframes in the feature_batches list vertically into one dataframe.

# Feature_batches contains the dominant topics and topic probabilities for the
# remaining LDA records outside the initial 50k sample.
lda_features_remaining = pd.concat(
    feature_batches,
    ignore_index=True
)

# Specify only the LDA feature columns
cols = (
    ['Complaint ID', 'dominant_topic']
    + [
        col for col in lda_features_remaining.columns
        if col.startswith('topic_')
    ]
)

# Force both dataframes to have the same columns
lda_features_remaining = lda_features_remaining[cols]
lda_features_sample = lda_features_sample[cols]

# Concatenate the 50k LDA sample with the remaining records
lda_features_all = pd.concat(
    [lda_features_sample, lda_features_remaining],
    ignore_index=True
)

print(f'Sample rows: {len(lda_features_sample):,}')
print(f'Remaining rows: {len(lda_features_remaining):,}')
print(f'Total LDA feature rows: {len(lda_features_all):,}')

Sample rows: 50,000
Remaining rows: 348,004
Total LDA feature rows: 398,004

## Export LDA Features

In [24]:
lda_features_all.head()

,Complaint ID,dominant_topic,topic_0_prob,topic_1_prob,topic_2_prob,topic_3_prob,topic_4_prob,topic_5_prob,topic_6_prob,topic_7_prob,...,topic_10_prob,topic_11_prob,topic_12_prob,topic_13_prob,topic_14_prob,topic_15_prob,topic_16_prob,topic_17_prob,topic_18_prob,topic_19_prob
0,7148773,9,0.043817,0.000485,0.296702,0.000485,0.000485,0.106598,0.000485,0.093212,...,0.000485,0.000485,0.000485,0.152601,0.000485,0.000485,0.000485,0.000485,0.000485,0.000485
1,5432970,11,0.002941,0.002941,0.002941,0.002941,0.002941,0.002941,0.194197,0.002941,...,0.002941,0.495463,0.002941,0.002941,0.260341,0.002941,0.002941,0.002941,0.002941,0.002941
2,3850335,4,0.000099,0.000099,0.238830,0.000099,0.435029,0.000099,0.017631,0.009844,...,0.030489,0.000099,0.071104,0.000099,0.000099,0.171067,0.000099,0.000099,0.000099,0.000099
3,12076787,19,0.000446,0.000446,0.166560,0.000446,0.000446,0.000446,0.049077,0.000446,...,0.000446,0.000446,0.151287,0.000446,0.164227,0.000446,0.000446,0.000446,0.044577,0.418023
4,7974309,4,0.003125,0.003125,0.003125,0.003125,0.601591,0.003125,0.003125,0.003125,...,0.003125,0.342159,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125,0.003125

In [25]:
lda_features_all.info()

<class 'pandas.DataFrame'>
RangeIndex: 398004 entries, 0 to 398003
Data columns (total 22 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Complaint ID    398004 non-null  int64
 1   dominant_topic  398004 non-null  int64
 2   topic_0_prob    398004 non-null  float64
 3   topic_1_prob    398004 non-null  float64
 4   topic_2_prob    398004 non-null  float64
 5   topic_3_prob    398004 non-null  float64
 6   topic_4_prob    398004 non-null  float64
 7   topic_5_prob    398004 non-null  float64
 8   topic_6_prob    398004 non-null  float64
 9   topic_7_prob    398004 non-null  float64
 10  topic_8_prob    398004 non-null  float64
 11  topic_9_prob    398004 non-null  float64
 12  topic_10_prob   398004 non-null  float64
 13  topic_11_prob   398004 non-null  float64
 14  topic_12_prob   398004 non-null  float64
 15  topic_13_prob   398004 non-null  float64
 16  topic_14_prob   398004 non-null  float64
 17  topic_15_prob   398004 non-null  float64
 18  topic_16_prob   398004 non-null  float64
 19  topic_17_prob   398004 non-null  float64
 20  topic_18_prob   398004 non-null  float64
 21  topic_19_prob   398004 non-null  float64
dtypes: float64(20), int64(2)
memory usage: 66.8 MB

In [26]:
# Export parquet ONLY containing the LDA feature columns.
# To be joined back to the full dataframe and cluster features in the next notebook.
OUTPUT_PATH = '../data/processed/lda_features.parquet'

lda_features_all.to_parquet(
    OUTPUT_PATH,
    index=False
)

print(lda_features_all.shape)

(398004, 22)