In [1]:
# %pip install polars
# %pip install duckdb

In [2]:
import pandas as pd
import duckdb
import polars as pl

In [3]:
# Original code loading csv into parquet

# duckdb.sql("""
# COPY (
#     SELECT * FROM read_csv_auto('complaints.csv')
# )
# TO 'complaints.parquet'
# (FORMAT PARQUET);
# """)

In [4]:
# Load parquet into lazy dataframe and display the head
df = pl.scan_parquet("complaints.parquet")
df.head(5).collect()

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ Product   ┆ Sub-produ ┆ Issue     ┆ … ┆ Company   ┆ Timely    ┆ Consumer  ┆ Complain │
│ received  ┆ ---       ┆ ct        ┆ ---       ┆   ┆ response  ┆ response? ┆ disputed? ┆ t ID     │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ to        ┆ ---       ┆ ---       ┆ ---      │
│ date      ┆           ┆ str       ┆           ┆   ┆ consumer  ┆ bool      ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2020-07-0 ┆ Credit    ┆ Credit    ┆ Incorrect ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3730948  │
│ 6         ┆ reporting ┆ reporting ┆ informati ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ , credit  ┆           ┆ on on     ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ repai…    ┆           ┆ your …    ┆   ┆           ┆           ┆           ┆          │
│ 2019-12-2 ┆ Credit    ┆ General-p ┆ Advertisi ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3477549  │
│ 6         ┆ card or   ┆ urpose    ┆ ng and    ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ prepaid   ┆ credit    ┆ marketing ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ card      ┆ card or…  ┆ , inc…    ┆   ┆           ┆           ┆           ┆          │
│ 2020-05-0 ┆ Credit    ┆ Credit    ┆ Incorrect ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3642453  │
│ 8         ┆ reporting ┆ reporting ┆ informati ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ , credit  ┆           ┆ on on     ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ repai…    ┆           ┆ your …    ┆   ┆           ┆           ┆           ┆          │
│ 2024-01-0 ┆ Credit    ┆ Credit    ┆ Incorrect ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 8113747  │
│ 5         ┆ reporting ┆ reporting ┆ informati ┆   ┆ with non- ┆           ┆           ┆          │
│           ┆ or other  ┆           ┆ on on     ┆   ┆ monetary  ┆           ┆           ┆          │
│           ┆ pers…     ┆           ┆ your …    ┆   ┆ relie…    ┆           ┆           ┆          │
│ 2024-01-2 ┆ Credit    ┆ Credit    ┆ Improper  ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 8191825  │
│ 1         ┆ reporting ┆ reporting ┆ use of    ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ or other  ┆           ┆ your      ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ pers…     ┆           ┆ report    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [33]:
# Complaints by product
products = duckdb.sql("""
    SELECT
        Product,
        COUNT(*) AS complaints
    FROM 'complaints.parquet'
    GROUP BY Product
    ORDER BY complaints DESC
""")

products

┌──────────────────────────────────────────────────────────────────────────────┬────────────┐
│                                   Product                                    │ complaints │
│                                   varchar                                    │   int64    │
├──────────────────────────────────────────────────────────────────────────────┼────────────┤
│ Credit reporting or other personal consumer reports                          │    9570678 │
│ Credit reporting, credit repair services, or other personal consumer reports │    2163800 │
│ Debt collection                                                              │    1077479 │
│ Mortgage                                                                     │     446996 │
│ Checking or savings account                                                  │     361214 │
│ Credit card                                                                  │     307090 │
│ Credit card or prepaid card                                                  │     206364 │
│ Money transfer, virtual currency, or money service                           │     176333 │
│ Credit reporting                                                             │     140426 │
│ Student loan                                                                 │     125962 │
│ Vehicle loan or lease                                                        │      93475 │
│ Bank account or service                                                      │      86200 │
│ Consumer Loan                                                                │      31560 │
│ Payday loan, title loan, or personal loan                                    │      30625 │
│ Payday loan, title loan, personal loan, or advance loan                      │      30055 │
│ Prepaid card                                                                 │      20785 │
│ Debt or credit management                                                    │       8551 │
│ Payday loan                                                                  │       5528 │
│ Money transfers                                                              │       5354 │
│ Other financial service                                                      │       1056 │
│ Virtual currency                                                             │         18 │
└──────────────────────────────────────────────────────────────────────────────┴────────────┘
  21 rows                                                                         2 columns

In [11]:
# Number of records with non-null narratives and Yes/No for dispute
count_narratives_all = (
    df
    .filter(
        pl.col('Consumer complaint narrative').is_not_null()
        & pl.col('Consumer disputed?').is_in(['Yes', 'No'])
    )
    .select(pl.len().alias('count_narratives_all'))
    .collect()
)

print(f'The number of records with valid narratives AND yes/no in disputed: {count_narratives_all}')

The number of records with valid narratives AND yes/no in disputed: shape: (1, 1)
┌──────────────────────┐
│ count_narratives_all │
│ ---                  │
│ u32                  │
╞══════════════════════╡
│ 163960               │
└──────────────────────┘

In [51]:
# Number of records with non-null narratives - all products
count_narratives_all = (
    df
    .filter(
        pl.col('Consumer complaint narrative').is_not_null()
    )
    .select(pl.len().alias('count_narratives_all'))
    .collect()
)

print(f'The number of records with valid narratives: {count_narratives_all}')

The number of records with valid narratives: shape: (1, 1)
┌──────────────────────┐
│ count_narratives_all │
│ ---                  │
│ u32                  │
╞══════════════════════╡
│ 3770248              │
└──────────────────────┘

In [27]:
# Top 10 companies - valid narratives

duckdb.sql("""
    SELECT
        Company,
        COUNT(*) AS narrative_count
    FROM 'complaints.parquet'
    WHERE "Consumer complaint narrative" IS NOT NULL
    GROUP BY Company
    ORDER BY narrative_count DESC
    LIMIT 10
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌────────────────────────────────────────┬─────────────────┐
│                Company                 │ narrative_count │
│                varchar                 │      int64      │
├────────────────────────────────────────┼─────────────────┤
│ EQUIFAX, INC.                          │          815798 │
│ TRANSUNION INTERMEDIATE HOLDINGS, INC. │          773419 │
│ Experian Information Solutions Inc.    │          736063 │
│ CAPITAL ONE FINANCIAL CORPORATION      │           68103 │
│ JPMORGAN CHASE & CO.                   │           62507 │
│ WELLS FARGO & COMPANY                  │           58537 │
│ BANK OF AMERICA, NATIONAL ASSOCIATION  │           56410 │
│ CITIBANK, N.A.                         │           53439 │
│ Block, Inc.                            │           46319 │
│ SYNCHRONY FINANCIAL                    │           33727 │
└────────────────────────────────────────┴─────────────────┘
  10 rows                                        2 columns

In [29]:
# Top 5 companies non-credit - valid narratives and Yes/No in dispute
duckdb.sql("""
    SELECT
        Company,
        COUNT(*) AS narrative_count
    FROM 'complaints.parquet'
    WHERE "Consumer complaint narrative" IS NOT NULL
      AND "Consumer disputed?" IN ('Yes', 'No')
      AND Company IN (
          'CAPITAL ONE FINANCIAL CORPORATION',
          'JPMORGAN CHASE & CO.',
          'WELLS FARGO & COMPANY',
          'BANK OF AMERICA, NATIONAL ASSOCIATION',
          'CITIBANK, N.A.'
      )
    GROUP BY Company
    ORDER BY narrative_count DESC
""")

┌───────────────────────────────────────┬─────────────────┐
│                Company                │ narrative_count │
│                varchar                │      int64      │
├───────────────────────────────────────┼─────────────────┤
│ WELLS FARGO & COMPANY                 │            7503 │
│ BANK OF AMERICA, NATIONAL ASSOCIATION │            7254 │
│ CITIBANK, N.A.                        │            6993 │
│ JPMORGAN CHASE & CO.                  │            6260 │
│ CAPITAL ONE FINANCIAL CORPORATION     │            3763 │
└───────────────────────────────────────┴─────────────────┘

In [32]:
# Filter the LazyFrame to Mortgage, Checking/Savings, Credit card, Bank account
bank_products_df = df.filter(
    pl.col('Product').is_in([
        'Mortgage',
        'Checking or savings account',
        'Credit card',
        'Credit card or prepaid card',
        'Bank account or service' 
    ])
)

bank_products_df.limit(5).collect()

shape: (5, 18)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Date      ┆ Product   ┆ Sub-produ ┆ Issue     ┆ … ┆ Company   ┆ Timely    ┆ Consumer  ┆ Complain │
│ received  ┆ ---       ┆ ct        ┆ ---       ┆   ┆ response  ┆ response? ┆ disputed? ┆ t ID     │
│ ---       ┆ str       ┆ ---       ┆ str       ┆   ┆ to        ┆ ---       ┆ ---       ┆ ---      │
│ date      ┆           ┆ str       ┆           ┆   ┆ consumer  ┆ bool      ┆ str       ┆ i64      │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2019-12-2 ┆ Credit    ┆ General-p ┆ Advertisi ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3477549  │
│ 6         ┆ card or   ┆ urpose    ┆ ng and    ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ prepaid   ┆ credit    ┆ marketing ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ card      ┆ card or…  ┆ , inc…    ┆   ┆           ┆           ┆           ┆          │
│ 2019-12-2 ┆ Checking  ┆ Other     ┆ Managing  ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3475858  │
│ 0         ┆ or        ┆ banking   ┆ an        ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ savings   ┆ product   ┆ account   ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ account   ┆ or servi… ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2019-09-0 ┆ Checking  ┆ Checking  ┆ Managing  ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3363680  │
│ 4         ┆ or        ┆ account   ┆ an        ┆   ┆ with      ┆           ┆           ┆          │
│           ┆ savings   ┆           ┆ account   ┆   ┆ monetary  ┆           ┆           ┆          │
│           ┆ account   ┆           ┆           ┆   ┆ relief    ┆           ┆           ┆          │
│ 2019-11-1 ┆ Credit    ┆ General-p ┆ Problem   ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3442136  │
│ 8         ┆ card or   ┆ urpose    ┆ with a    ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ prepaid   ┆ credit    ┆ purchase  ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ card      ┆ card or…  ┆ shown …   ┆   ┆           ┆           ┆           ┆          │
│ 2020-06-0 ┆ Checking  ┆ Checking  ┆ Managing  ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3684669  │
│ 5         ┆ or        ┆ account   ┆ an        ┆   ┆ with expl ┆           ┆           ┆          │
│           ┆ savings   ┆           ┆ account   ┆   ┆ anation   ┆           ┆           ┆          │
│           ┆ account   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [52]:
# Bank products with valid narratives and Yes/No dispute
count_narratives = (
    bank_products_df
    .filter(
        pl.col('Consumer complaint narrative').is_not_null()
    )
    .select(pl.len().alias('count_narratives'))
    .collect()
)

print(f'The number of records in bank_products with valid narratives: {count_narratives}')

The number of records in bank_products with valid narratives: shape: (1, 1)
┌──────────────────┐
│ count_narratives │
│ ---              │
│ u32              │
╞══════════════════╡
│ 556498           │
└──────────────────┘

In [31]:
# Filter the original LazyFrame to Mortage only
mortgage_df = df.filter(pl.col('Product') == 'Mortgage')

mortgage_df.head().collect()

shape: (5, 18)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Date      ┆ Product  ┆ Sub-produ ┆ Issue     ┆ … ┆ Company   ┆ Timely    ┆ Consumer  ┆ Complaint │
│ received  ┆ ---      ┆ ct        ┆ ---       ┆   ┆ response  ┆ response? ┆ disputed? ┆ ID        │
│ ---       ┆ str      ┆ ---       ┆ str       ┆   ┆ to        ┆ ---       ┆ ---       ┆ ---       │
│ date      ┆          ┆ str       ┆           ┆   ┆ consumer  ┆ bool      ┆ str       ┆ i64       │
│           ┆          ┆           ┆           ┆   ┆ ---       ┆           ┆           ┆           │
│           ┆          ┆           ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2019-01-0 ┆ Mortgage ┆ Conventio ┆ Strugglin ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3120489   │
│ 9         ┆          ┆ nal home  ┆ g to pay  ┆   ┆ with expl ┆           ┆           ┆           │
│           ┆          ┆ mortgage  ┆ mortgage  ┆   ┆ anation   ┆           ┆           ┆           │
│ 2014-03-2 ┆ Mortgage ┆ Other     ┆ Loan serv ┆ … ┆ Closed    ┆ true      ┆ No        ┆ 782303    │
│ 7         ┆          ┆ mortgage  ┆ icing,    ┆   ┆ with expl ┆           ┆           ┆           │
│           ┆          ┆           ┆ payments, ┆   ┆ anation   ┆           ┆           ┆           │
│           ┆          ┆           ┆ escr…     ┆   ┆           ┆           ┆           ┆           │
│ 2024-01-1 ┆ Mortgage ┆ Conventio ┆ Trouble   ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 8179245   │
│ 8         ┆          ┆ nal home  ┆ during    ┆   ┆ with expl ┆           ┆           ┆           │
│           ┆          ┆ mortgage  ┆ payment   ┆   ┆ anation   ┆           ┆           ┆           │
│           ┆          ┆           ┆ process   ┆   ┆           ┆           ┆           ┆           │
│ 2020-01-2 ┆ Mortgage ┆ Other     ┆ Trouble   ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3509026   │
│ 4         ┆          ┆ type of   ┆ during    ┆   ┆ with expl ┆           ┆           ┆           │
│           ┆          ┆ mortgage  ┆ payment   ┆   ┆ anation   ┆           ┆           ┆           │
│           ┆          ┆           ┆ process   ┆   ┆           ┆           ┆           ┆           │
│ 2019-08-1 ┆ Mortgage ┆ Conventio ┆ Trouble   ┆ … ┆ Closed    ┆ true      ┆ N/A       ┆ 3341452   │
│ 5         ┆          ┆ nal home  ┆ during    ┆   ┆ with expl ┆           ┆           ┆           │
│           ┆          ┆ mortgage  ┆ payment   ┆   ┆ anation   ┆           ┆           ┆           │
│           ┆          ┆           ┆ process   ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [53]:
# Print sample of 10 narratives
sample_narratives = (
    mortgage_df
    .filter(pl.col('Consumer complaint narrative').is_not_null())
    .select('Consumer complaint narrative')
    .collect()
    .sample(n=10, shuffle=True)
)

narratives = sample_narratives['Consumer complaint narrative'].to_list()

for i, narrative in enumerate(narratives, start=1):
    print(f'\n--- Narrative {i} ---')
    print(narrative)

--- Narrative 1 ---
I received a letter from an unknown bank, M & T bank, saying they are the alleged new servicer. I have not received any communication from the previous alleged servicer XXXX XXXX. Now I am getting numerous phone calls and mailings using my private intellectual property regarding the alleged mortgage, without my consent. list of calls and XXXX XXXX, XX/XX/year> XXXX, XX/XX/year> XXXX, XX/XX/year> XXXX, XX/XX/year> XXXX, XX/XX/year> XXXX.

--- Narrative 2 ---
XXXX : XXXX this agent persisted me on a daily basis and when I decided not to continue they pressurized me to complete assuring me they where best and would benefit me. I explained my concerns with closing costs and they assured me it was normal. I subsequently have been advised its above average. I was also told they would consolidate all our debt only to find most of it will be consumed by closing costs. Then insisted we close to lock in rate and now they going ahead and ensuring process would be efficient. Since signing I have not heard from company! Sent emails and phoned but they unable to assist and was not able to speak to anyone who could assist. I have no idea what is going on and now told payments due XX/XX/XXXX when I was told it would be 2 months of no payments and no information about debt consolidation which was reason to start with. Now we continue to incur interest and the closing fee of {$17000.00} is excessive as I told them! This is our house and we have worked hard for it only to be poorly managed.

We continue to incur costs and nobody is helping!

--- Narrative 3 ---
loan care mortgage took over my loan from XXXX on appx. XX/XX/12019 since then i have had nothing but problems with them. newest problem is they lost my payment of XXXX i sent to them on XX/XX/XXXX cashiers check to exact address they said. now they said i sent to a p.o. box in wrong state. I cant get a hold of them .you wait over hour to talk to a totally uniformed agent, who will hang up on you as soon as you ask a question they cant answer. i am XXXX years old and worried they are trying to steal my home. please help.

--- Narrative 4 ---
I have attached a letter regarding PHH mortgage. They're very unethical and purposely dragged the modification they were trying to do with me since XXXX of XXXX. In the end, which is XXXX of XXXX, they told me, because the amount of XXXX that I got behind since XXXX of XXXX, I was over their XXXX percent rule.

I will tell you that when the forebearance period ended in XXXX of XXXX. PHH mortgage was the only servicer that did not try to lower my payment. I have several homes, i was on the brink of losing, due to covid 19.

All other mortgage companies, lowered my payment and helped me. Phh on the other hand at XX/XX/XXXX did not offer any help, and when I asked for help, they dragged this entire modification all the way from XXXX of XXXX til XXXX of XXXX to tell me, sorry, XXXX XXXX, you dont qualify, either sell your home, or give us your deed in lieu, they also refused to refinance my home, because I missed my payments, and even when i paid them to make the account current. PHH told me that I would have to wait one year.

This mortgage company had the intent to foreclose on my, because my primary residence has a lot of equity, and PHH knows this. They are the most horrible mortgage company out there.

They only hire employees from overseas that are not trained, and they just tell me XXXX XXXX XXXX XXXX send this and send that, they gave me wrong emails, wrong information, and every agent I talked to would tell me a different document was requested. I can not believe that this company is even allowed to operate, when they are not in the business there logo which is " Helping homeowners is what we do '' This statement is fraud.

They need to change their motto to " Helping homeowners IS NOT WHAT WE DO '' Is the correct statement.
I am frustrated beyond words. I have been them on time for 10 years, and when covid 19 hit, my Mom died, my dad foot is XXXX, I have a young son XXXX XXXX XXXX. I am single Mom tried to support my entire family with problems.

PHH mortgage needs to be investigated for their unethical practices of trying to take homes way from vulnerable people. I am sure I am not the only one out there, that has endured 6 months of phones calls, and documentation to be told SORRY ABOUT THAT. In a very customer services reps that care more about their roosters and dogs in the background, as I am begging for help.

I hope someone reads this, because this was the worse experience I have had, and it has just been trauma after trauma.

--- Narrative 5 ---
I XXXX XXXX applied for a loan modification with Bank of America, for years they denied me a modification then this year they said if I make trial payments they will give me a modification. I made XXXX trial payments and then they send me a loan modification agreement. And I cant accept it because they want an outrages amount of money that I do n't have. They did n't forgive me the past dew amount. I know there are government programs that exist for these situations that are supposed to help the consumer like my self. But I do n't see those programs working. Please help me with this.

--- Narrative 6 ---
In XXXX started with XXXX XXXX and in XXXX XXXX sold my contract to OCMBC. Now OCMBC sold my contract to XXXX in XXXX. OCMBC has not sent my XXXX payment to XXXX yet. I was assured there would be no problem with the payment. I'm now experiencing issues with my credit and it effecting opportunities.

--- Narrative 7 ---
I apologize that this complaint is being filed late - I only recently learned of the service that the Bureau of Consumer Financial Protection provides. This complaint is related to our mortgage with Bank of America for our property at XXXX XXXX XXXX, XXXX, CA XXXX. In XX/XX/XXXX because our property was severely under-water ( we owed about {$300000.00} more than the property was worth ), we began the short-sale process. In XX/XX/XXXX, a buyer was identified and we sent the proposal to Bank of America. After months and months of delays, with numerous requests for more and more paperwork ( very frequently it was a request for information that had already been provided, several times XXXX, Bank of America finally approved the short sale. We received a letter from them ( see attached ) outlining the details of the approval. We complied with all requests. As you can see in the attached document, B of A indicated that we would receive {$22000.00} as part of a government program. Once the short-sale was approved, it took the buyer a little longer to get his financing approved - about 3 weeks. Because of this delay ( and despite the months of delay we had experienced with Bank of America XXXX, we were told that we were no longer eligible for the {$22000.00} because the program had expired. This seems very unfair to us because we had been diligent in complying with all the bank 's requests in a timely manner. Additionally, we had a credit card with Bank of America for many years ( unrelated to our mortgage with them XXXX. During the short-sale process, the bank sent us notice that our credit card was discontinued AND that we were no longer entitled to the rewards we had earned on the card ( rewards totaled about {$900.00} XXXX. It just seems that Bank of America acted unfairly with us.

--- Narrative 8 ---
I have a balloon mortgage that came due XX/XX/XXXX. I called XX/XX/XXXX to refinance. The agent I spoke to said it was too early to refinance call back in 2 or 3 months. I called back XX/XX/XXXX and they said I didn't qualify. I had to make a minimum of 6 or 7 calls, being put on hold, being transferred from department to department. The customer service agent said it was too late to refinance I should have started the process earlier.
XX/XX/XXXX I received a letter stating they would no longer be taking payments from me.
In late XXXX and XXXX, I called, and it to me 3 weeks to get through. I stated I owe one last payment of {$230.00} for XXXX and the representative said they didn't see that I owned anything but the balloon payment.
XXXX I received an alert on my credit that I had late payments from PHH.
I called and spoke to 3 representatives and they all said I own only the balloon payment.
I spoke with Case Manager on XX/XX/XXXX and he said I own 3 XXXX dollar payments. I explained that I tried to pay but was told I didn't own XXXX payment. He insisted I did and that's why I was getting late reporting. I said I happy to pay. He said it would be XXXX extra to make a payment. I refused to pay an extra {$17.00} for a payment I have tried to make for 2 months. He said I could mail in a check for no charge when I asked him for the address he said : " PHH may reject it because it was late. '' My complaints 1 ) unable to contact PHH in timely manner hours on hold or just in a loop with no connection 2 ) Customer Service giving wrong information 3 ) PHH mailing letters that contradict Customer Service information 4 )  Unable to pay via PHH website, XXXX XXXX because phone lines are busy 5 ) Customer Servers charging & XXXX per payment 6 ) Not giving alternatives for payment methods 7 ) Insisting I must make my payments even though I received a letter stating they would no longer be taking my payments 8 ) lastly, the Case Manager I spoke with was condescending in his demeanor and contradicting PHH letter to stop payments. He said " you owe the XXXX payments '' and I agreed with him and I want to pay the money but adding XXXX per payment seems excessive and not being able to pay via the PHH website.
I

--- Narrative 9 ---
I was set up to complete a mortgage with Quicken Loans INC. the third party appraiser, turned in an appraisal document with words mispelled, missing or incorrect information, and failed to fill out the certification that the individual was physically present at the property. Quicken Loans failed to contact me to get the matter resolved. I as an individual had to gather documents from XXXX, and local tax office to show the invalid information contained within the report. Quicken Loans failed to contact the consumer to update him of the process, the consumer had to reach out to Quicken Loans multiple times, and finally Quicken Loans in an email admitted that the XXXX party appraisal management company found that the comparable properties turned in by the consumer should have been considered. Quicken Loans after nearly a week and a half has failed to resolve the situation. Quicken Loans stated via telephone that the issue was the consumers fault. Quicken Loans has failed to refund any deposit made by the consumer. Quicken Loans has failed to follow any good faith gestures in their short comings.

--- Narrative 10 ---
We obtained a construction loan from Synovus bank to build our dream house. The loan amount was {$460.00}, XXXX at an interest rate of 4.375 %, to be disbursed in progress payments. We have received {$280000.00}. The monthly payment for this amount is {$1100.00}, which we have paid faithfully. On XX/XX/22, Synovus arbitrarily raised our payment to {$2400.00}. They said that this amount includes principal and interest on the total loan amount of $ XXXX. We replied that we could not be expected to pay principal $ interest on funds that Synovus never disbursed. Furthermore, we agreed to pay the XXXX, if the total loan amount was given to us. At present, the facts are as follows : 1 ) Synovus has reported us as late, to the credit bureaus for 13 consecutive months, even though we pay the proper amount {$1100.00} monthly.
2 ) Synovus has ruined our credit which makes it impossible to refinance this mortgage. 3 ) Synovus refuses to release the additional funds we needed to complete building our home, yet they want to force us to pay principal & interest on funds in their possession.

In [16]:
# Save mortgage-only to parquet
# mortgage_df.sink_parquet('mortgage_only_complaints.parquet')

In [15]:
# Load parquet into pandas dataframe
pandas_mortgage_df = pd.read_parquet('mortgage_only_complaints.parquet')

In [17]:
pandas_mortgage_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 446996 entries, 0 to 446995
Data columns (total 18 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Date received                 446996 non-null  object
 1   Product                       446996 non-null  object
 2   Sub-product                   446996 non-null  object
 3   Issue                         446996 non-null  object
 4   Sub-issue                     69135 non-null   object
 5   Consumer complaint narrative  141969 non-null  object
 6   Company public response       154269 non-null  object
 7   Company                       446996 non-null  object
 8   State                         441354 non-null  object
 9   ZIP code                      441915 non-null  object
 10  Tags                          86201 non-null   object
 11  Consumer consent provided?    441503 non-null  object
 12  Submitted via                 446996 non-null  object
 13  Date sent to company          446996 non-null  object
 14  Company response to consumer  446995 non-null  object
 15  Timely response?              446996 non-null  bool
 16  Consumer disputed?            446996 non-null  object
 17  Complaint ID                  446996 non-null  int64
dtypes: bool(1), int64(1), object(16)
memory usage: 58.4+ MB

In [18]:
# Percentage of records with non-blank/non-null narratives
count_non_null = pandas_mortgage_df['Consumer complaint narrative'].count()
print(f'The number of records in the mortgage df with non-blank/non-null narratives: {count_non_null}')
total_rows = len(pandas_mortgage_df)

pct_with_narratives = round(((count_non_null / total_rows) * 100), 2)
print(f'The percentage of records with non-blank complaint narratives is: {pct_with_narratives:.2f}%')

The number of records in the mortgage df with non-blank/non-null narratives: 141969
The percentage of records with non-blank complaint narratives is: 31.76%

In [19]:
# Value counts in "Consumer disputed?"
pandas_mortgage_df['Consumer disputed?'].value_counts()

Consumer disputed?
N/A    220156
No     175471
Yes     51369
Name: count, dtype: int64

In [46]:
# Value counts in "Timely"
pandas_mortgage_df['Timely response?'].value_counts()

Timely response?
True     438969
False      8027
Name: count, dtype: int64

In [20]:
# Percentage of records with valid yes/no in disputed column
non_na = pandas_mortgage_df[
    (pandas_mortgage_df['Consumer disputed?'] == 'Yes') | 
    (pandas_mortgage_df['Consumer disputed?'] == 'No')
    ]

count_non_na = len(non_na)
total_rows = len(pandas_mortgage_df)

pct_with_yes_no = round(((count_non_na / total_rows) * 100), 2)
print(f'The percentage of records with yes/no in disputed: {pct_with_yes_no:.2f}%')

# Count of records with yes/no disputed AND valid narrative
count_narratives = non_na['Consumer complaint narrative'].count()
print(f'The number of records with valid narratives AND yes/no in disputed: {count_narratives}')

The percentage of records with yes/no in disputed: 50.75%
The number of records with valid narratives AND yes/no in disputed: 32788

In [50]:
# Percentage of records with valid yes/no in disputed column
non_na = pandas_mortgage_df[
    (pandas_mortgage_df['Timely response?'] == True) | 
    (pandas_mortgage_df['Timely response?'] == False)
    ]

count_non_na = len(non_na)
total_rows = len(pandas_mortgage_df)

pct_with_yes_no = round(((count_non_na / total_rows) * 100), 2)
print(f'The percentage of records with yes/no in disputed: {pct_with_yes_no:.2f}%')

# Count of records with timely AND valid narrative
count_narratives = non_na['Consumer complaint narrative'].count()
print(f'The number of records with valid narratives AND yes/no in disputed: {count_narratives}')

The percentage of records with yes/no in disputed: 100.00%
The number of records with valid narratives AND yes/no in disputed: 141969

In [44]:
# Value counts in "Timely"
pandas_mortgage_df['Timely response?'].value_counts()

Timely response?
True     438969
False      8027
Name: count, dtype: int64

In [43]:
# Shift back to parquet file for SQL queries
# Count narratives by year - mortgage only
duckdb.sql("""
    SELECT
        YEAR("Date received") AS year, "Timely response?" as timely,
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'mortgage_only_complaints.parquet'
    GROUP BY year, timely
    ORDER BY year
""")

┌───────┬─────────┬────────────┬────────────┐
│ year  │ timely  │ complaints │ narratives │
│ int64 │ boolean │   int64    │   int64    │
├───────┼─────────┼────────────┼────────────┤
│  2011 │ false   │        171 │          0 │
│  2011 │ true    │       1105 │          0 │
│  2012 │ true    │      36336 │          0 │
│  2012 │ false   │       1772 │          0 │
│  2013 │ true    │      48902 │          0 │
│  2013 │ false   │        495 │          0 │
│  2014 │ false   │        846 │          0 │
│  2014 │ true    │      42095 │          0 │
│  2015 │ false   │        663 │        204 │
│  2015 │ true    │      41666 │      12097 │
│    ·  │  ·      │        ·   │        ·   │
│    ·  │  ·      │        ·   │        ·   │
│    ·  │  ·      │        ·   │        ·   │
│  2022 │ true    │      22893 │      12086 │
│  2022 │ false   │        393 │        199 │
│  2023 │ true    │      22616 │      12743 │
│  2023 │ false   │        238 │        140 │
│  2024 │ false   │        251 │        143 │
│  2024 │ true    │      21198 │      12069 │
│  2025 │ false   │        374 │        218 │
│  2025 │ true    │      24287 │      13774 │
│  2026 │ false   │        163 │         46 │
│  2026 │ true    │      10064 │       2498 │
└───────┴─────────┴────────────┴────────────┘
  32 rows (20 shown)              4 columns

In [40]:
# Shift back to parquet file for SQL queries
# Count narratives by year - all products
duckdb.sql("""
    SELECT
        YEAR("Date received") AS year, "Consumer disputed?" as dispute,
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'complaints.parquet'
    WHERE dispute = 'N/A'
    GROUP BY year, dispute
    ORDER BY year
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────┬─────────┬────────────┬────────────┐
│ year  │ dispute │ complaints │ narratives │
│ int64 │ varchar │   int64    │   int64    │
├───────┼─────────┼────────────┼────────────┤
│  2017 │ N/A     │     170469 │      83614 │
│  2018 │ N/A     │     257137 │     118393 │
│  2019 │ N/A     │     277249 │     124836 │
│  2020 │ N/A     │     444231 │     174306 │
│  2021 │ N/A     │     495956 │     203564 │
│  2022 │ N/A     │     800312 │     337165 │
│  2023 │ N/A     │    1292069 │     487417 │
│  2024 │ N/A     │    2734293 │     814390 │
│  2025 │ N/A     │    5442769 │    1221783 │
│  2026 │ N/A     │    2207174 │      40820 │
└───────┴─────────┴────────────┴────────────┘
  10 rows                         4 columns

In [40]:
# Shift back to parquet file for SQL queries
# Count narratives by year - all products
duckdb.sql("""
    SELECT
        YEAR("Date received") AS year, "Consumer disputed?" as dispute,
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'complaints.parquet'
    WHERE dispute = 'N/A'
    GROUP BY year, dispute
    ORDER BY year
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────┬─────────┬────────────┬────────────┐
│ year  │ dispute │ complaints │ narratives │
│ int64 │ varchar │   int64    │   int64    │
├───────┼─────────┼────────────┼────────────┤
│  2017 │ N/A     │     170469 │      83614 │
│  2018 │ N/A     │     257137 │     118393 │
│  2019 │ N/A     │     277249 │     124836 │
│  2020 │ N/A     │     444231 │     174306 │
│  2021 │ N/A     │     495956 │     203564 │
│  2022 │ N/A     │     800312 │     337165 │
│  2023 │ N/A     │    1292069 │     487417 │
│  2024 │ N/A     │    2734293 │     814390 │
│  2025 │ N/A     │    5442769 │    1221783 │
│  2026 │ N/A     │    2207174 │      40820 │
└───────┴─────────┴────────────┴────────────┘
  10 rows                         4 columns

In [40]:
# Shift back to parquet file for SQL queries
# Count narratives by year - all products
duckdb.sql("""
    SELECT
        YEAR("Date received") AS year, "Timely?" as timely,
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'complaints.parquet'
    WHERE dispute = 'N/A'
    GROUP BY year, dispute
    ORDER BY year
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌───────┬─────────┬────────────┬────────────┐
│ year  │ dispute │ complaints │ narratives │
│ int64 │ varchar │   int64    │   int64    │
├───────┼─────────┼────────────┼────────────┤
│  2017 │ N/A     │     170469 │      83614 │
│  2018 │ N/A     │     257137 │     118393 │
│  2019 │ N/A     │     277249 │     124836 │
│  2020 │ N/A     │     444231 │     174306 │
│  2021 │ N/A     │     495956 │     203564 │
│  2022 │ N/A     │     800312 │     337165 │
│  2023 │ N/A     │    1292069 │     487417 │
│  2024 │ N/A     │    2734293 │     814390 │
│  2025 │ N/A     │    5442769 │    1221783 │
│  2026 │ N/A     │    2207174 │      40820 │
└───────┴─────────┴────────────┴────────────┘
  10 rows                         4 columns

In [21]:
# Shift back to parquet file for SQL queries
# Count narratives by year - mortgage only - timely
duckdb.sql("""
    SELECT
        YEAR("Date received") AS year,
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'mortgage_only_complaints.parquet'
    GROUP BY year
    ORDER BY year
""")

┌───────┬────────────┬────────────┐
│ year  │ complaints │ narratives │
│ int64 │   int64    │   int64    │
├───────┼────────────┼────────────┤
│  2011 │       1276 │          0 │
│  2012 │      38108 │          0 │
│  2013 │      49397 │          0 │
│  2014 │      42941 │          0 │
│  2015 │      42329 │      12301 │
│  2016 │      41455 │      15765 │
│  2017 │      30559 │      13137 │
│  2018 │      24568 │      10270 │
│  2019 │      22701 │      10033 │
│  2020 │      24652 │      12467 │
│  2021 │      26533 │      14080 │
│  2022 │      23286 │      12285 │
│  2023 │      22854 │      12883 │
│  2024 │      21449 │      12212 │
│  2025 │      24661 │      13992 │
│  2026 │      10227 │       2544 │
└───────┴────────────┴────────────┘
  16 rows               3 columns

In [22]:
# Narratives by sub-product - mortgage only
duckdb.sql("""
    SELECT
        "Sub-product",
        COUNT(*) AS complaints,
        COUNT("Consumer complaint narrative") AS narratives
    FROM 'mortgage_only_complaints.parquet'
    GROUP BY "Sub-product"
    ORDER BY narratives DESC
""")

┌────────────────────────────────────────────┬────────────┬────────────┐
│                Sub-product                 │ complaints │ narratives │
│                  varchar                   │   int64    │   int64    │
├────────────────────────────────────────────┼────────────┼────────────┤
│ Conventional home mortgage                 │     131596 │      64855 │
│ FHA mortgage                               │      60692 │      26569 │
│ Conventional fixed mortgage                │      70593 │      14557 │
│ VA mortgage                                │      22012 │      11597 │
│ Home equity loan or line of credit (HELOC) │      13749 │       6187 │
│ Other type of mortgage                     │      17521 │       5672 │
│ Conventional adjustable mortgage (ARM)     │      25380 │       4975 │
│ Other mortgage                             │      86612 │       3236 │
│ Home equity loan or line of credit         │      11622 │       2102 │
│ Reverse mortgage                           │       5254 │       1499 │
│ Manufactured home loan                     │        682 │        378 │
│ USDA mortgage                              │        621 │        342 │
│ Second mortgage                            │        662 │          0 │
└────────────────────────────────────────────┴────────────┴────────────┘
  13 rows                                                    3 columns

In [23]:
# Min/Max and Avg characters in the narratives
duckdb.sql("""
SELECT
    MIN(LENGTH("Consumer complaint narrative")) AS min_chars,
    AVG(LENGTH("Consumer complaint narrative")) AS avg_chars,
    MAX(LENGTH("Consumer complaint narrative")) AS max_chars
FROM 'mortgage_only_complaints.parquet'
WHERE "Consumer complaint narrative" IS NOT NULL;
""")

┌───────────┬────────────────────┬───────────┐
│ min_chars │     avg_chars      │ max_chars │
│   int64   │       double       │   int64   │
├───────────┼────────────────────┼───────────┤
│        13 │ 1666.9142066225725 │     32317 │
└───────────┴────────────────────┴───────────┘

In [24]:
# Top 20 longest narratives with product and sub-product
duckdb.sql("""
SELECT
    LENGTH("Consumer complaint narrative") AS chars,
    "Issue",
    "Sub-product"
FROM 'mortgage_only_complaints.parquet'
WHERE "Consumer complaint narrative" IS NOT NULL
ORDER BY chars DESC
LIMIT 20;
""")

┌───────┬─────────────────────────────────────────────────────────────┬────────────────────────────┐
│ chars │                            Issue                            │        Sub-product         │
│ int64 │                           varchar                           │          varchar           │
├───────┼─────────────────────────────────────────────────────────────┼────────────────────────────┤
│ 32317 │ Closing on a mortgage                                       │ Other type of mortgage     │
│ 31922 │ Trouble during payment process                              │ FHA mortgage               │
│ 31737 │ Trouble during payment process                              │ Conventional home mortgage │
│ 31645 │ Trouble during payment process                              │ FHA mortgage               │
│ 31636 │ Trouble during payment process                              │ Conventional home mortgage │
│ 31611 │ Struggling to pay mortgage                                  │ FHA mortgage               │
│ 31498 │ Closing on a mortgage                                       │ FHA mortgage               │
│ 31463 │ Struggling to pay mortgage                                  │ Conventional home mortgage │
│ 31435 │ Trouble during payment process                              │ VA mortgage                │
│ 31423 │ Applying for a mortgage or refinancing an existing mortgage │ Other type of mortgage     │
│ 31369 │ Closing on a mortgage                                       │ Other type of mortgage     │
│ 31359 │ Closing on a mortgage                                       │ Conventional home mortgage │
│ 31305 │ Closing on a mortgage                                       │ Conventional home mortgage │
│ 31301 │ Struggling to pay mortgage                                  │ Conventional home mortgage │
│ 31190 │ Closing on a mortgage                                       │ VA mortgage                │
│ 31182 │ Closing on a mortgage                                       │ VA mortgage                │
│ 31177 │ Struggling to pay mortgage                                  │ Conventional home mortgage │
│ 31174 │ Applying for a mortgage or refinancing an existing mortgage │ VA mortgage                │
│ 31163 │ Closing on a mortgage                                       │ VA mortgage                │
│ 31128 │ Struggling to pay mortgage                                  │ Conventional home mortgage │
└───────┴─────────────────────────────────────────────────────────────┴────────────────────────────┘
  20 rows                                                                                3 columns

In [25]:
# Narratives by issue
duckdb.sql("""
SELECT
    Issue,
    COUNT(*) AS narratives
FROM 'mortgage_only_complaints.parquet'
WHERE "Consumer complaint narrative" IS NOT NULL
GROUP BY Issue
ORDER BY narratives DESC;
""")

┌──────────────────────────────────────────────────────────────────────────────────┬────────────┐
│                                      Issue                                       │ narratives │
│                                     varchar                                      │   int64    │
├──────────────────────────────────────────────────────────────────────────────────┼────────────┤
│ Trouble during payment process                                                   │      54142 │
│ Struggling to pay mortgage                                                       │      26004 │
│ Loan servicing, payments, escrow account                                         │      14720 │
│ Applying for a mortgage or refinancing an existing mortgage                      │      14534 │
│ Loan modification,collection,foreclosure                                         │      10788 │
│ Closing on a mortgage                                                            │      10481 │
│ Application, originator, mortgage broker                                         │       3744 │
│ Incorrect information on your report                                             │       2308 │
│ Settlement process and costs                                                     │       2248 │
│ Credit decision / Underwriting                                                   │       1288 │
│ Problem with a credit reporting company's investigation into an existing problem │        658 │
│ Problem with a company's investigation into an existing problem                  │        505 │
│ Improper use of your report                                                      │        341 │
│ Credit monitoring or identity theft protection services                          │         93 │
│ Unable to get your credit report or credit score                                 │         77 │
│ Problem with fraud alerts or security freezes                                    │         38 │
└──────────────────────────────────────────────────────────────────────────────────┴────────────┘
  16 rows                                                                             2 columns